import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { proxyUrl } from '../config';
import type { AthenaBridge } from './UnityAthena';

/**
 * Neural text-to-speech generated by the Athena backend and played by the
 * embedded Unity avatar. Browser/OS SpeechSynthesis is intentionally not used.
 */

const STORAGE_KEY = 'guardian_tts_enabled';
const GENERATION_TIMEOUT_MS = 30_000;

interface SpeechResponse {
  audioBase64: string;
  sampleRate: number;
  channels: number;
}

interface UnitySpeechPayload extends SpeechResponse {
  requestId: string;
}

interface PendingSpeech {
  id: string;
  abort: AbortController;
  timer: number;
  onEnd?: () => void;
}

export interface Speech {
  isSupported: boolean;
  enabled: boolean;
  attachUnity: (bridge: AthenaBridge) => void;
  toggle: () => void;
  speak: (text: string, onEnd?: () => void) => void;
  cancel: () => void;
}

function pcmDurationMs(audioBase64: string, sampleRate: number, channels: number): number {
  const padding = audioBase64.endsWith('==') ? 2 : audioBase64.endsWith('=') ? 1 : 0;
  const byteLength = Math.max(0, Math.floor((audioBase64.length * 3) / 4) - padding);
  const samplesPerChannel = byteLength / 2 / Math.max(1, channels);
  return Math.ceil((samplesPerChannel / Math.max(1, sampleRate)) * 1000);
}

export function useSpeech(): Speech {
  const [isSupported, setIsSupported] = useState(false);
  const [enabled, setEnabled] = useState<boolean>(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored === null ? true : stored === 'true';
  });
  const enabledRef = useRef(enabled);
  enabledRef.current = enabled;

  const bridgeRef = useRef<AthenaBridge | null>(null);
  const pendingRef = useRef<PendingSpeech | null>(null);

  const finish = useCallback((requestId?: string) => {
    const pending = pendingRef.current;
    if (!pending || (requestId && pending.id !== requestId)) return;
    pendingRef.current = null;
    pending.abort.abort();
    window.clearTimeout(pending.timer);
    try {
      pending.onEnd?.();
    } catch (error) {
      console.warn('useSpeech: onEnd failed', error);
    }
  }, []);

  const cancel = useCallback(() => {
    bridgeRef.current?.sendToGameObject('AthenaBridge', 'StopSpeech');
    finish();
  }, [finish]);

  const attachUnity = useCallback((bridge: AthenaBridge) => {
    bridgeRef.current = bridge;
    setIsSupported(true);
  }, []);

  useEffect(() => {
    const onEnded = (event: Event) => {
      const requestId = (event as CustomEvent<{ requestId?: string }>).detail?.requestId;
      finish(requestId);
    };
    const onError = (event: Event) => {
      const requestId = (event as CustomEvent<{ requestId?: string }>).detail?.requestId;
      console.warn('Unity could not play Athena speech');
      finish(requestId);
    };

    window.addEventListener('athena-unity-speech-ended', onEnded);
    window.addEventListener('athena-unity-speech-error', onError);
    return () => {
      window.removeEventListener('athena-unity-speech-ended', onEnded);
      window.removeEventListener('athena-unity-speech-error', onError);
      bridgeRef.current?.sendToGameObject('AthenaBridge', 'StopSpeech');
      const pending = pendingRef.current;
      if (pending) {
        pending.abort.abort();
        window.clearTimeout(pending.timer);
        pendingRef.current = null;
      }
    };
  }, [finish]);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, String(enabled));
    if (!enabled) cancel();
  }, [cancel, enabled]);

  const speak = useCallback(
    (text: string, onEnd?: () => void) => {
      if (!enabledRef.current || !bridgeRef.current || !text?.trim()) {
        onEnd?.();
        return;
      }

      cancel();
      const id = crypto.randomUUID();
      const abort = new AbortController();
      const timer = window.setTimeout(() => {
        console.warn('useSpeech: voice generation timed out');
        finish(id);
      }, GENERATION_TIMEOUT_MS);
      pendingRef.current = { id, abort, timer, onEnd };

      void fetch(proxyUrl('/api/v1/speech'), {
        method: 'POST',
        credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: text.trim() }),
        signal: abort.signal,
      })
        .then(async (response) => {
          if (!response.ok) throw new Error(`Speech request failed (${response.status})`);
          return (await response.json()) as SpeechResponse;
        })
        .then((audio) => {
          if (pendingRef.current?.id !== id || !bridgeRef.current) return;
          if (!audio.audioBase64 || !audio.sampleRate || !audio.channels) {
            throw new Error('Speech response did not contain playable PCM audio');
          }

          const payload: UnitySpeechPayload = { requestId: id, ...audio };
          bridgeRef.current.sendToGameObject(
            'AthenaBridge',
            'PlaySpeech',
            JSON.stringify(payload)
          );

          window.clearTimeout(pendingRef.current.timer);
          pendingRef.current.timer = window.setTimeout(
            () => finish(id),
            pcmDurationMs(audio.audioBase64, audio.sampleRate, audio.channels) + 2000
          );
        })
        .catch((error: unknown) => {
          if ((error as { name?: string }).name !== 'AbortError') {
            console.warn('useSpeech: speech failed', error);
            finish(id);
          }
        });
    },
    [cancel, finish]
  );

  const toggle = useCallback(() => setEnabled((value) => !value), []);

  return useMemo(
    () => ({ isSupported, enabled, attachUnity, toggle, speak, cancel }),
    [attachUnity, cancel, enabled, isSupported, speak, toggle]
  );
}
