import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { proxyUrl } from '../config';
import type { AthenaBridge } from './UnityAthena';

/**
 * Neural text-to-speech generated by the Athena backend and played by the
 * embedded Unity avatar. Browser/OS SpeechSynthesis is intentionally not used.
 *
 * Generation takes seconds, so speech is split into two phases: `prepare()`
 * starts fetching the audio immediately and `play()` hands it to Unity. That
 * lets the chat hold Athena's text reveal until the voice can start with it
 * (see AthenaConsole's voice-sync gate); `speak()` remains as the one-shot
 * prepare-then-play convenience.
 */

const STORAGE_KEY = 'guardian_tts_enabled';
const GENERATION_TIMEOUT_MS = 30_000;
// Singing runs on a slower model: ~15 s for a four-line song.
const SING_GENERATION_TIMEOUT_MS = 75_000;
// Said in her normal voice while a song generates. Short on purpose: each
// is its own quick generation, and the point is to answer immediately.
const SONG_INTROS = [
  'Ooh, a song. Give me a second to warm up.',
  'Okay, okay. Let me find the tune.',
  "I'd love to. One moment.",
  'Alright, clearing my throat.',
];

interface SpeechResponse {
  audioBase64: string;
  sampleRate: number;
  channels: number;
}

interface UnitySpeechPayload extends SpeechResponse {
  requestId: string;
}

interface PendingSpeech {
  id: string;
  abort: AbortController;
  timer: number;
  onEnd?: () => void;
}

export interface PreparedSpeech {
  /**
   * Resolves true once the audio is fetched and can start instantly; false if
   * generation failed, timed out, was cancelled, or TTS is disabled.
   */
  ready: Promise<boolean>;
  /** Hand the audio to Unity. Calls onEnd immediately if there is no audio. */
  play: (onEnd?: () => void) => void;
  cancel: () => void;
}

export interface Speech {
  isSupported: boolean;
  enabled: boolean;
  attachUnity: (bridge: AthenaBridge) => void;
  toggle: () => void;
  /** Begin generating audio for `text` without playing it yet. `sing` sings it. */
  prepare: (text: string, options?: { sing?: boolean }) => PreparedSpeech;
  speak: (text: string, onEnd?: () => void) => void;
  cancel: () => void;
}

function pcmDurationMs(audioBase64: string, sampleRate: number, channels: number): number {
  const padding = audioBase64.endsWith('==') ? 2 : audioBase64.endsWith('=') ? 1 : 0;
  const byteLength = Math.max(0, Math.floor((audioBase64.length * 3) / 4) - padding);
  const samplesPerChannel = byteLength / 2 / Math.max(1, channels);
  return Math.ceil((samplesPerChannel / Math.max(1, sampleRate)) * 1000);
}

export function useSpeech(): Speech {
  const [isSupported, setIsSupported] = useState(false);
  const [enabled, setEnabled] = useState<boolean>(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored === null ? true : stored === 'true';
  });
  const enabledRef = useRef(enabled);
  enabledRef.current = enabled;

  const bridgeRef = useRef<AthenaBridge | null>(null);
  const pendingRef = useRef<PendingSpeech | null>(null);
  // The prepared speech that last took the voice; a song waiting behind its
  // intro only plays if it still holds it.
  const ownerRef = useRef<string | null>(null);

  const finish = useCallback((requestId?: string) => {
    const pending = pendingRef.current;
    if (!pending || (requestId && pending.id !== requestId)) return;
    pendingRef.current = null;
    pending.abort.abort();
    window.clearTimeout(pending.timer);
    try {
      pending.onEnd?.();
    } catch (error) {
      console.warn('useSpeech: onEnd failed', error);
    }
  }, []);

  const cancel = useCallback(() => {
    ownerRef.current = null;
    bridgeRef.current?.sendToGameObject('AthenaBridge', 'StopSpeech');
    finish();
  }, [finish]);

  const attachUnity = useCallback((bridge: AthenaBridge) => {
    bridgeRef.current = bridge;
    setIsSupported(true);
  }, []);

  useEffect(() => {
    const onEnded = (event: Event) => {
      const requestId = (event as CustomEvent<{ requestId?: string }>).detail?.requestId;
      finish(requestId);
    };
    const onError = (event: Event) => {
      const requestId = (event as CustomEvent<{ requestId?: string }>).detail?.requestId;
      console.warn('Unity could not play Athena speech');
      finish(requestId);
    };

    window.addEventListener('athena-unity-speech-ended', onEnded);
    window.addEventListener('athena-unity-speech-error', onError);
    return () => {
      window.removeEventListener('athena-unity-speech-ended', onEnded);
      window.removeEventListener('athena-unity-speech-error', onError);
      bridgeRef.current?.sendToGameObject('AthenaBridge', 'StopSpeech');
      const pending = pendingRef.current;
      if (pending) {
        pending.abort.abort();
        window.clearTimeout(pending.timer);
        pendingRef.current = null;
      }
    };
  }, [finish]);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, String(enabled));
    if (!enabled) cancel();
  }, [cancel, enabled]);

  /**
   * Fetch one generated clip. Resolves null on failure, timeout, or when
   * `signal` aborts. Each clip has its own controller so a spoken intro timing
   * out never takes the song down with it.
   */
  const fetchAudio = useCallback(
    (text: string, sing: boolean, signal: AbortSignal): Promise<SpeechResponse | null> =>
      new Promise((resolve) => {
        const own = new AbortController();
        if (signal.aborted) own.abort();
        else signal.addEventListener('abort', () => own.abort(), { once: true });
        const timer = window.setTimeout(() => {
          console.warn('useSpeech: voice generation timed out');
          own.abort();
          resolve(null);
        }, sing ? SING_GENERATION_TIMEOUT_MS : GENERATION_TIMEOUT_MS);

        void fetch(proxyUrl('/api/v1/speech'), {
          method: 'POST',
          credentials: 'include',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(sing ? { text, style: 'sing' } : { text }),
          signal: own.signal,
        })
          .then(async (response) => {
            if (!response.ok) throw new Error(`Speech request failed (${response.status})`);
            return (await response.json()) as SpeechResponse;
          })
          .then((payload) => {
            if (!payload.audioBase64 || !payload.sampleRate || !payload.channels) {
              throw new Error('Speech response did not contain playable PCM audio');
            }
            resolve(payload);
          })
          .catch((error: unknown) => {
            if ((error as { name?: string }).name !== 'AbortError') {
              console.warn('useSpeech: speech failed', error);
            }
            resolve(null);
          })
          .finally(() => window.clearTimeout(timer));
      }),
    []
  );

  const prepare = useCallback(
    (text: string, options?: { sing?: boolean }): PreparedSpeech => {
      const trimmed = text?.trim();
      const sing = options?.sing === true;
      const id = crypto.randomUUID();
      const abort = new AbortController();
      let cancelled = false;
      let intro: SpeechResponse | null = null;
      let audio: SpeechResponse | null = null;

      const active = enabledRef.current && !!trimmed;
      const audioP = active ? fetchAudio(trimmed, sing, abort.signal) : Promise.resolve(null);
      // A song takes ~15 s to generate. A short spoken line (a few seconds, on
      // the fast model) covers the wait so she answers right away.
      const introP =
        active && sing
          ? fetchAudio(SONG_INTROS[Math.floor(Math.random() * SONG_INTROS.length)], false, abort.signal)
          : Promise.resolve(null);
      void audioP.then((payload) => {
        audio = payload;
      });
      void introP.then((payload) => {
        intro = payload;
      });

      // Ready as soon as something can start: the intro for a song, otherwise
      // the clip itself. False only when there is nothing at all to play.
      const ready = new Promise<boolean>((resolve) => {
        void introP.then((payload) => payload && resolve(!cancelled));
        void audioP.then((payload) => payload && resolve(!cancelled));
        void Promise.all([introP, audioP]).then(([a, b]) => !a && !b && resolve(false));
      });

      const playClip = (clipId: string, payload: SpeechResponse, onEnd?: () => void) => {
        // Stop anything currently speaking before starting this clip.
        cancel();
        const timer = window.setTimeout(
          () => finish(clipId),
          pcmDurationMs(payload.audioBase64, payload.sampleRate, payload.channels) + 2000
        );
        // The intro gets a throwaway controller: finishing it must not abort
        // the song that is still being fetched.
        pendingRef.current = { id: clipId, abort: clipId === id ? abort : new AbortController(), timer, onEnd };
        const unityPayload: UnitySpeechPayload = { requestId: clipId, ...payload };
        bridgeRef.current?.sendToGameObject('AthenaBridge', 'PlaySpeech', JSON.stringify(unityPayload));
      };

      const play = (onEnd?: () => void) => {
        if (cancelled || (!intro && !audio) || !enabledRef.current || !bridgeRef.current) {
          onEnd?.();
          return;
        }
        // Played once the intro ends — unless something else has taken the
        // voice since (a newer reply, a cancel, voice switched off).
        const playMain = () => {
          void audioP.then((payload) => {
            if (!payload || cancelled || ownerRef.current !== id || !enabledRef.current || !bridgeRef.current) {
              onEnd?.();
              return;
            }
            playClip(id, payload, onEnd);
          });
        };
        if (intro) playClip(`${id}:intro`, intro, playMain);
        else playClip(id, audio!, onEnd);
        ownerRef.current = id;
      };

      const cancelPrepared = () => {
        cancelled = true;
        abort.abort();
        if (pendingRef.current?.id.startsWith(id)) cancel();
      };

      return { ready, play, cancel: cancelPrepared };
    },
    [cancel, fetchAudio, finish]
  );

  const speak = useCallback(
    (text: string, onEnd?: () => void) => {
      const prepared = prepare(text);
      void prepared.ready.then((ok) => {
        if (ok) prepared.play(onEnd);
        else onEnd?.();
      });
    },
    [prepare]
  );

  const toggle = useCallback(() => setEnabled((value) => !value), []);

  return useMemo(
    () => ({ isSupported, enabled, attachUnity, toggle, prepare, speak, cancel }),
    [attachUnity, cancel, enabled, isSupported, prepare, speak, toggle]
  );
}
