import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { proxyUrl } from '../config';
import type { AthenaBridge } from './UnityAthena';
import warmupHumArpeggioUrl from './voice/warmup-hum-arpeggio.json?url';
import warmupHumScaleUrl from './voice/warmup-hum-scale.json?url';
import warmupMimiUrl from './voice/warmup-mimi.json?url';

/**
 * Neural text-to-speech generated by the Athena backend and played by the
 * embedded Unity avatar. Browser/OS SpeechSynthesis is intentionally not used.
 *
 * Generation takes seconds, so speech is split into two phases: `prepare()`
 * starts fetching the audio immediately and `play()` hands it to Unity. That
 * lets the chat hold Athena's text reveal until the voice can start with it
 * (see AthenaConsole's voice-sync gate); `speak()` remains as the one-shot
 * prepare-then-play convenience.
 */

const STORAGE_KEY = 'guardian_tts_enabled';
const GENERATION_TIMEOUT_MS = 30_000;
// Singing runs on a slower model: ~15 s for a four-line song.
const SING_GENERATION_TIMEOUT_MS = 75_000;
// Vocal warm-ups she hums between her spoken lead-in and a song, recorded
// once in her own voice (Pro TTS) so they play instantly. Fetched only the
// first time she sings.
const WARMUP_URLS = [warmupHumArpeggioUrl, warmupHumScaleUrl, warmupMimiUrl];
// One always plays; the rest only cover a song that is still generating.
const MAX_WARMUPS = 3;

let warmupsPromise: Promise<SpeechResponse[]> | null = null;
function loadWarmups(): Promise<SpeechResponse[]> {
  if (!warmupsPromise) {
    const loading = Promise.all(
      WARMUP_URLS.map((url) =>
        fetch(url)
          .then((response) => (response.ok ? (response.json() as Promise<SpeechResponse>) : null))
          .catch(() => null)
      )
    ).then((clips) => clips.filter((clip): clip is SpeechResponse => !!clip?.audioBase64));
    warmupsPromise = loading;
    // A failed load shouldn't stick for the rest of the session.
    void loading.then((clips) => {
      if (!clips.length && warmupsPromise === loading) warmupsPromise = null;
    });
  }
  return warmupsPromise;
}

interface SpeechResponse {
  audioBase64: string;
  sampleRate: number;
  channels: number;
}

interface UnitySpeechPayload extends SpeechResponse {
  requestId: string;
}

interface PendingSpeech {
  id: string;
  abort: AbortController;
  timer: number;
  onEnd?: () => void;
}

export interface PreparedSpeech {
  /**
   * Resolves true once the audio is fetched and can start instantly; false if
   * generation failed, timed out, was cancelled, or TTS is disabled.
   */
  ready: Promise<boolean>;
  /** Hand the audio to Unity. Calls onEnd immediately if there is no audio. */
  play: (onEnd?: () => void) => void;
  cancel: () => void;
}

export interface Speech {
  isSupported: boolean;
  enabled: boolean;
  attachUnity: (bridge: AthenaBridge) => void;
  toggle: () => void;
  /**
   * Begin generating audio for `text` without playing it yet. With `lyrics`,
   * `text` is her spoken lead-in and the lyrics are sung after a warm-up hum.
   */
  prepare: (text: string, options?: { lyrics?: string }) => PreparedSpeech;
  speak: (text: string, onEnd?: () => void) => void;
  cancel: () => void;
}

function pcmDurationMs(audioBase64: string, sampleRate: number, channels: number): number {
  const padding = audioBase64.endsWith('==') ? 2 : audioBase64.endsWith('=') ? 1 : 0;
  const byteLength = Math.max(0, Math.floor((audioBase64.length * 3) / 4) - padding);
  const samplesPerChannel = byteLength / 2 / Math.max(1, channels);
  return Math.ceil((samplesPerChannel / Math.max(1, sampleRate)) * 1000);
}

export function useSpeech(): Speech {
  const [isSupported, setIsSupported] = useState(false);
  const [enabled, setEnabled] = useState<boolean>(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored === null ? true : stored === 'true';
  });
  const enabledRef = useRef(enabled);
  enabledRef.current = enabled;

  const bridgeRef = useRef<AthenaBridge | null>(null);
  const pendingRef = useRef<PendingSpeech | null>(null);
  // The prepared speech that last took the voice; a song waiting behind its
  // intro only plays if it still holds it.
  const ownerRef = useRef<string | null>(null);

  const finish = useCallback((requestId?: string) => {
    const pending = pendingRef.current;
    if (!pending || (requestId && pending.id !== requestId)) return;
    pendingRef.current = null;
    pending.abort.abort();
    window.clearTimeout(pending.timer);
    try {
      pending.onEnd?.();
    } catch (error) {
      console.warn('useSpeech: onEnd failed', error);
    }
  }, []);

  /** Stop the clip that is playing, without giving up the voice. */
  const stopCurrent = useCallback(() => {
    bridgeRef.current?.sendToGameObject('AthenaBridge', 'StopSpeech');
    finish();
  }, [finish]);

  const cancel = useCallback(() => {
    ownerRef.current = null;
    stopCurrent();
  }, [stopCurrent]);

  const attachUnity = useCallback((bridge: AthenaBridge) => {
    bridgeRef.current = bridge;
    setIsSupported(true);
  }, []);

  useEffect(() => {
    const onEnded = (event: Event) => {
      const requestId = (event as CustomEvent<{ requestId?: string }>).detail?.requestId;
      finish(requestId);
    };
    const onError = (event: Event) => {
      const requestId = (event as CustomEvent<{ requestId?: string }>).detail?.requestId;
      console.warn('Unity could not play Athena speech');
      finish(requestId);
    };

    window.addEventListener('athena-unity-speech-ended', onEnded);
    window.addEventListener('athena-unity-speech-error', onError);
    return () => {
      window.removeEventListener('athena-unity-speech-ended', onEnded);
      window.removeEventListener('athena-unity-speech-error', onError);
      bridgeRef.current?.sendToGameObject('AthenaBridge', 'StopSpeech');
      const pending = pendingRef.current;
      if (pending) {
        pending.abort.abort();
        window.clearTimeout(pending.timer);
        pendingRef.current = null;
      }
    };
  }, [finish]);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, String(enabled));
    if (!enabled) cancel();
  }, [cancel, enabled]);

  /**
   * Fetch one generated clip. Resolves null on failure, timeout, or when
   * `signal` aborts. Each clip has its own controller so a spoken intro timing
   * out never takes the song down with it.
   */
  const fetchAudio = useCallback(
    (text: string, sing: boolean, signal: AbortSignal): Promise<SpeechResponse | null> =>
      new Promise((resolve) => {
        const own = new AbortController();
        if (signal.aborted) own.abort();
        else signal.addEventListener('abort', () => own.abort(), { once: true });
        const timer = window.setTimeout(() => {
          console.warn('useSpeech: voice generation timed out');
          own.abort();
          resolve(null);
        }, sing ? SING_GENERATION_TIMEOUT_MS : GENERATION_TIMEOUT_MS);

        void fetch(proxyUrl('/api/v1/speech'), {
          method: 'POST',
          credentials: 'include',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(sing ? { text, style: 'sing' } : { text }),
          signal: own.signal,
        })
          .then(async (response) => {
            if (!response.ok) throw new Error(`Speech request failed (${response.status})`);
            return (await response.json()) as SpeechResponse;
          })
          .then((payload) => {
            if (!payload.audioBase64 || !payload.sampleRate || !payload.channels) {
              throw new Error('Speech response did not contain playable PCM audio');
            }
            resolve(payload);
          })
          .catch((error: unknown) => {
            if ((error as { name?: string }).name !== 'AbortError') {
              console.warn('useSpeech: speech failed', error);
            }
            resolve(null);
          })
          .finally(() => window.clearTimeout(timer));
      }),
    []
  );

  const prepare = useCallback(
    (text: string, options?: { lyrics?: string }): PreparedSpeech => {
      const trimmed = text?.trim();
      const lyrics = options?.lyrics?.trim() || '';
      const id = crypto.randomUUID();
      const abort = new AbortController();
      let cancelled = false;
      let audio: SpeechResponse | null = null;
      let song: SpeechResponse | null = null;
      let songFailed = false;

      const active = enabledRef.current && !!trimmed;
      const audioP = active ? fetchAudio(trimmed, false, abort.signal) : Promise.resolve(null);
      // A song generates (~15 s) while she says her lead-in and hums a
      // warm-up; the hum is what keeps the switch to singing from being abrupt.
      const songP = active && lyrics ? fetchAudio(lyrics, true, abort.signal) : Promise.resolve(null);
      const warmupsP = active && lyrics ? loadWarmups() : Promise.resolve([] as SpeechResponse[]);
      const warmupStart = Math.floor(Math.random() * WARMUP_URLS.length);
      void audioP.then((payload) => {
        audio = payload;
      });
      void songP.then((payload) => {
        song = payload;
        songFailed = !!lyrics && !payload;
      });

      // Ready as soon as something can start: the spoken line, or the song if
      // the spoken line failed. False only when there is nothing to play.
      const ready = new Promise<boolean>((resolve) => {
        void audioP.then((payload) => payload && resolve(!cancelled));
        void songP.then((payload) => payload && resolve(!cancelled));
        void Promise.all([audioP, songP]).then(([a, b]) => !a && !b && resolve(false));
      });

      // Something else may take the voice while a song is still coming (a
      // newer reply, a cancel, Voice switched off); then the rest is dropped.
      const stillOwner = () =>
        !cancelled && ownerRef.current === id && enabledRef.current && !!bridgeRef.current;

      const playClip = (clipId: string, payload: SpeechResponse, onEnd?: () => void) => {
        stopCurrent();
        const timer = window.setTimeout(
          () => finish(clipId),
          pcmDurationMs(payload.audioBase64, payload.sampleRate, payload.channels) + 2000
        );
        // Only the final clip owns `abort`: finishing the lead-in or a hum
        // must not abort the song that is still being fetched.
        pendingRef.current = { id: clipId, abort: clipId === id ? abort : new AbortController(), timer, onEnd };
        const unityPayload: UnitySpeechPayload = { requestId: clipId, ...payload };
        bridgeRef.current?.sendToGameObject('AthenaBridge', 'PlaySpeech', JSON.stringify(unityPayload));
      };

      // After the lead-in: always one warm-up (the bridge from talking to
      // singing), more only while the song is still generating, then the song.
      const towardSong = (warmups: number, onEnd?: () => void) => {
        if (!stillOwner() || songFailed) {
          onEnd?.();
          return;
        }
        if (song && warmups > 0) {
          playClip(id, song, onEnd);
          return;
        }
        void warmupsP.then((clips) => {
          if (!stillOwner() || songFailed) {
            onEnd?.();
            return;
          }
          if (song && warmups > 0) {
            playClip(id, song, onEnd);
          } else if (warmups < MAX_WARMUPS && clips.length) {
            const clip = clips[(warmupStart + warmups) % clips.length];
            playClip(`${id}:warmup${warmups}`, clip, () => towardSong(warmups + 1, onEnd));
          } else {
            void songP.then((payload) => {
              if (!payload || !stillOwner()) onEnd?.();
              else playClip(id, payload, onEnd);
            });
          }
        });
      };

      const play = (onEnd?: () => void) => {
        if (cancelled || !enabledRef.current || !bridgeRef.current || (!audio && !song)) {
          onEnd?.();
          return;
        }
        ownerRef.current = id;
        if (!lyrics) playClip(id, audio!, onEnd);
        else if (audio) playClip(`${id}:lead`, audio, () => towardSong(0, onEnd));
        else towardSong(0, onEnd);
      };

      const cancelPrepared = () => {
        cancelled = true;
        abort.abort();
        if (ownerRef.current === id) cancel();
      };

      return { ready, play, cancel: cancelPrepared };
    },
    [cancel, fetchAudio, finish, stopCurrent]
  );

  const speak = useCallback(
    (text: string, onEnd?: () => void) => {
      const prepared = prepare(text);
      void prepared.ready.then((ok) => {
        if (ok) prepared.play(onEnd);
        else onEnd?.();
      });
    },
    [prepare]
  );

  const toggle = useCallback(() => setEnabled((value) => !value), []);

  return useMemo(
    () => ({ isSupported, enabled, attachUnity, toggle, prepare, speak, cancel }),
    [attachUnity, cancel, enabled, isSupported, prepare, speak, toggle]
  );
}
